from jinja2 import Template
import sys
import os
import json
import argparse
from datetime import datetime
from mydb import send_mail
from mydb import mydb_config

__version__ = '1.0.0'
__date__ = 'Oct 24, 2025'
__maintainer__ = 'John Dey jfdey@fredhutch.org'

""" build_email.py
    Send a message to all users of MyDB from email list generated by the MyDB app 

    build and send email to users of MyDB. The address data is generated by the
    MyDB UI in JSON format.
    The addresses data has the following fields.
    "address" = {'user', 'DisplayName', 'containers': [containerName, DB Image, Uptime]

    read a JinJa2 formated text file for the message, and format an email for each user
    content variables for JinJa template: [User, sent_date, supportOrganizatioin, containers]
"""

def generate_email(subject, template_content, addresses):
    """ format a custom email message with Jinia2 from <template_content>
    and send to users in `addresses` with email <subject>
    """
    # Create a Jinja2 template object
    template = Template(template_content)
    now = datetime.now()

    context = {}
    context['sent_date'] = now.strftime("%B %d, %Y")
    context['supportEmail'] = mydb_config.supportEmail
    context['supportOrganizatioin'] = mydb_config.supportOrganizatioin

    for user in addresses.keys():
        context['User'] = addresses[user]['user']
        email_address = user
        context['containers'] = []
        for container in addresses[user]['containers']:
            container_text = f'{container[0]}, Type: {container[1]}  Uptime: {container[2]}'
            context['containers'].append(container_text)
        count = len(context['containers'])
        # Render Jinja2
        rendered_output = template.render(context)
        if '@' not in email_address:
            print(f'Invalid email: {email_address} User: {context['User']}')

        status = send_mail.send_mail(subject, rendered_output, [email_address])
        if status:
            print(f'error: {email_address} containers: {count}', file=sys.stderr)
        else:
            print(f'Sending to {email_address} containers: {count}')


def setup_parser():
    parser = argparse.ArgumentParser(description='Send email to all MyDB users')
    parser.add_argument('--version', action='version', version='%(prog)s ' +
                        __version__ + '  ' + __date__)
    parser.add_argument('--email-template', required=True,
                        help='email Jinja template ')
    parser.add_argument('--email-addresses', required=True,
                        help='email Jinja template ')
    parser.add_argument('--subject', required=True,
                        help='email subject; subject will be prefixed with "MyDB:"')
    return parser


def check_file(file_name):
    if not os.access(file_name, os.R_OK):
        print(f"File {file_name} is not readable.", file=sys.stderr)
        sys.exit(1)


def main():
    parser = setup_parser()
    args = parser.parse_args()

    check_file(args.email_addresses)
    with open(args.email_addresses, 'r') as f:
        addresses = json.load(f)

    check_file(args.email_template)
    with open(args.email_template, 'r') as f:
        email_body = f.read()
    generate_email("MyDB: " + args.subject, email_body, addresses)


if __name__ == "__main__":
    main()
