version: "3.8"

services:
    dbaas:
        image: ${github_org}/dbaas:2.0.1
        hostname: dbaas
        ports:
            - "5008:5000"
        volumes:
            - dbaas:/data
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
            - .env
        environment:
            TZ: "America/Los_Angeles"
            PYTHONUNBUFFERED: "1"
            FLASK_DEBUG: ${FLASK_DEBUG}
            FLASK_SECRET: "${FLASK_SECRET}"
            TASK_TOKEN: "${TASK_TOKEN}"
            AWS_BUCKET_NAME: "${AWS_BUCKET_NAME}"
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}" 
            SQLALCHEMY_ADMIN_URI: "${SQLALCHEMY_ADMIN_URI}"
            SQLALCHEMY_MIGRATE_URI: "${SQLALCHEMY_MIGRATE_URI}"
        labels:
            - "org.fredhutch.app.owner=jfdey@fredhutch.org"
            - "org.fredhutch.description=MyDB DBaaS Application"
            - "org.fredhutch.github.repo=db4sci"

volumes:
    dbaas:
        driver: ${SWARM_DRIVER}
        driver_opts:
            type: ${SWARM_DRIVER_TYPE}
            o: ${SWARM_OPTS}
            device: "${SWARM_DEVICE}/admin_db"
